// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GitAdd(arg1, arg2) {
  return window['go']['git']['GitCommands']['GitAdd'](arg1, arg2);
}

export function GitBranch(arg1, arg2) {
  return window['go']['git']['GitCommands']['GitBranch'](arg1, arg2);
}

export function GitBranchesList(arg1) {
  return window['go']['git']['GitCommands']['GitBranchesList'](arg1);
}

export function GitCommit(arg1, arg2) {
  return window['go']['git']['GitCommands']['GitCommit'](arg1, arg2);
}

export function GitDiff(arg1, arg2) {
  return window['go']['git']['GitCommands']['GitDiff'](arg1, arg2);
}

export function GitIgnore(arg1, arg2) {
  return window['go']['git']['GitCommands']['GitIgnore'](arg1, arg2);
}

export function GitInit(arg1) {
  return window['go']['git']['GitCommands']['GitInit'](arg1);
}

export function GitPush(arg1) {
  return window['go']['git']['GitCommands']['GitPush'](arg1);
}

export function GitReset(arg1, arg2) {
  return window['go']['git']['GitCommands']['GitReset'](arg1, arg2);
}

export function GitStatus(arg1) {
  return window['go']['git']['GitCommands']['GitStatus'](arg1);
}
