// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';

export function GitAdd(arg1:git.LocalRepository,arg2:string):Promise<string>;

export function GitBranch(arg1:git.LocalRepository,arg2:string):Promise<string>;

export function GitBranchesList(arg1:git.LocalRepository):Promise<Array<git.GitBranch>>;

export function GitCommit(arg1:git.LocalRepository,arg2:string):Promise<string>;

export function GitDiff(arg1:git.LocalRepository,arg2:string):Promise<string>;

export function GitIgnore(arg1:git.LocalRepository,arg2:string):Promise<void>;

export function GitInit(arg1:string):Promise<string>;

export function GitPush(arg1:git.LocalRepository):Promise<string>;

export function GitRemoteAdd(arg1:git.LocalRepository,arg2:string,arg3:string):Promise<string>;

export function GitRemotesList(arg1:git.LocalRepository):Promise<Array<git.GitRemote>>;

export function GitReset(arg1:git.LocalRepository,arg2:string):Promise<string>;

export function GitStatus(arg1:git.LocalRepository):Promise<git.GitStatus>;
