// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileContents(arg1, arg2) {
  return window['go']['main']['App']['FileContents'](arg1, arg2);
}

export function GetRepos() {
  return window['go']['main']['App']['GetRepos']();
}

export function UserAddGitRepo(arg1, arg2) {
  return window['go']['main']['App']['UserAddGitRepo'](arg1, arg2);
}

export function UserSelectGitRepoFolder(arg1) {
  return window['go']['main']['App']['UserSelectGitRepoFolder'](arg1);
}
