// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';

export function FileContents(arg1:string,arg2:string):Promise<string>;

export function GetRepos():Promise<Array<git.LocalRepository>>;

export function UserAddGitRepo(arg1:string,arg2:string):Promise<git.LocalRepository>;

export function UserSelectGitRepoFolder(arg1:boolean):Promise<string>;
